### ISSUE TITLE
Bug in cleanedClientUrl 

### ISSUE THREAD

**Issue by Foeyshell** [rajyraman/Levelup-for-Dynamics-CRM#3] opened 2016-05-27 22:46 UTC
Hi Very nice tool. But there is a bug. We are using on premise CRM 2016. and the tool doesn't work. and I found the bug is from  here.

 var cleanedClientUrl = clientUrl.lastIndexOf(orgUniqueName) === -1 ? clientUrl : clientUrl.substr(0, clientUrl.lastIndexOf('/'));

Our URL is: https://abc.hostingcompany.com
After the above line, cleannedClientUrl becomes https:/  --> this is a bug

Because event.origin is not equals to cleanedClientUrl, and it causes the script to return. 

Can this be fixed so that onpremise user will be able to use this great tool.

**Comment by rajyraman** [comment] 2016-05-28 02:33
Thank you for the report. I will look into this today.

**Comment by Foeyshell** [comment] 2016-05-29 03:54
Thanks for looking into it.

in the above example,

our url is: https://abc.hostingcompany.com
our org name is: abc

**Comment by rajyraman** [comment] 2016-05-30 00:26
I have fixed this issue and tested this locally. I am adding a couple more functions to the code. I will check this in and publish to the store when they are ready.

**Comment by Foeyshell** [comment] 2016-05-30 02:13
Great news, thanks so much for the quick action and looking forward to the new release.

**Comment by rajyraman** [comment] 2016-05-31 10:53
I have committed in the source with the changes. Can you please install the extension in Developer mode and see whether the issue is gone? Thank you.

**Comment by Foeyshell** [comment] 2016-06-01 04:38
It's working in developer mode, hooray! Thanks for the fix and made work for us!! Great tool!

**Comment by rajyraman** [comment] 2016-06-01 10:19
Fixed in v1.2

**Closed by rajyraman** 2016-06-01 10:19 UTC
