### ISSUE TITLE
Buttons don't do anything anymore

### ISSUE THREAD

**Issue by zaha** [rajyraman/Levelup-for-Dynamics-CRM#62] opened 2018-07-25 07:22 UTC
Hi everyone,

since today Levelup does not work for me at all anymore. None of the buttons do anything when clicked. I've tried it in multiple CRM 2013 and D365 instances.

Sporadically a CRM popup will show with an error, but I'm not sure if this is related:

```
<CrmScriptErrorReport>
  <ReportVersion>1.0</ReportVersion>
  <ScriptErrorDetails>
   <Message>Script error.</Message>
   <Line>0</Line>
   <URL></URL>
   <PageURL>/main.aspx#592093585</PageURL>
   <Function></Function>
   <CallStack>
   </CallStack>
  </ScriptErrorDetails>
  <ClientInformation>
   <BrowserUserAgent>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36</BrowserUserAgent>
   <BrowserLanguage>undefined</BrowserLanguage>
   <SystemLanguage>undefined</SystemLanguage>
   <UserLanguage>undefined</UserLanguage>
   <ScreenResolution>1920x1080</ScreenResolution>
   <ClientName>Web</ClientName>
   <ClientTime>2018-07-25T09:20:46</ClientTime>
  </ClientInformation>
  <ServerInformation>
    <OrgLanguage>1033</OrgLanguage>
    <OrgCulture>1033</OrgCulture>
    <UserLanguage>1033</UserLanguage>
    <UserCulture>1033</UserCulture>
    <OrgID>{2F1D442D-9728-E611-8144-005056BE4542}</OrgID>
    <UserID>{3F12AE6B-3FAF-E311-80BD-005056BE2160}</UserID>
    <CRMVersion>6.1.3.119</CRMVersion>
  </ServerInformation>
</CrmScriptErrorReport>
```

Please fix this ASAP, this tool is a life-saver and so helpful for my daily work. Thanks for developing it btw, much appeciated! :)

**Comment by jonckhje** [comment] 2018-07-25 08:20
Same here, unfortunately (without the described popup). 2016 on premise...

**Comment by Janes010** [comment] 2018-07-25 09:50
Same here (Dynamics CRM 2016 Online) and no popups. Hiopefully it will be fixed soon because I use this great tool very often.

**Comment by rajyraman** [comment] 2018-07-25 09:53
I just checked dynamics 365 on v9. It works. I will check on my local vm on v8 and see if there is any issue.

**Comment by jonckhje** [comment] 2018-07-25 10:24
Makes sense that v8 is giving trouble, on the other hand, OP mentioned D365 instances...

**Comment by zaha** [comment] 2018-07-25 10:48
> Makes sense that v8 is giving trouble, on the other hand, OP mentioned D365 instances...
Indeed, but we're also still running on v8 (forgot to mention that, sorry). So seems to be happening to versions before v9.

**Comment by rajyraman** [comment] 2018-07-25 11:17
The issue is only with v8. I published a new version to the store that should fix this issue. It should be available for update approx. in 1 hr.

**Comment by Ynoaparast** [comment] 2018-07-25 11:46
I had the same problem this morning. I just got the new version from the webshop, and after a restart of the browser, everything works like a charm so far :)    Thanks a lot for the quick response!

**Closed** 2018-07-25 11:55 UTC

**Comment by jonckhje** [comment] 2018-07-25 12:07
Fabulous! Thanks for the quick solution @rajyraman !!

Keep up the great work, wouldn't know what to do without your solution!

**Comment by Ynoaparast** [comment] 2018-07-25 12:17
I know what I would do - pester our CRM consultant with expensive questions on what fields are named and many other things ;)
