### ISSUE TITLE
Unable to search by users

### ISSUE THREAD

**Issue by ShellySteiger** [rajyraman/Levelup-for-Dynamics-CRM#285] opened 2023-03-24 11:28 UTC
Browser Version: [object Navigator]
    Extension Version: 3.6.3
    ----------------------------------------------------------
Have tried their name, first.last, their email and nothing works...

**Comment by ShellySteiger** [comment] 2023-03-24 11:29
this was working last week

**Comment by rajyraman** [comment] 2023-03-24 23:52
Duplicate of #280

**Closed by rajyraman** 2023-03-24 23:52 UTC
